//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asssignment_PSD_2201809140.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransactions
    {
        public int TransactionId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual HeaderTransaction HeaderTransaction { get; set; }
    }
}
